# Required build root directory. This should match
# the folder that composer.json is using in installer
# paths.
build:
  root: www

# Required temporary directory for build tasks.
temp: /tmp

# Symbolic links to create for the project
# Do not include the build root defined
# above in the destination.
symlinks:
  settings:
    source: local/settings.php
    destination: sites/default/settings.php
  settings.local:
    source: local/settings.local.php
    destination: sites/default/settings.local.php
  files:
    source: local/files
    destination: sites/default/files
  htaccess:
    source: .htaccess
    destination: .htaccess
    force: true

# Environments for deployments.
environments:
  production:
    git:
      uri: git@gitlab.com:[namespace]/[project].git
      branch: master
      # Optional sub-directory of the artifact repo to use.
      # The default is to build into the root of the git repo.
      sub_dir: docroot
    # Optionally specify which local root to use for the artifact repo.
    # - build_root (default) : Use the build root as the artifact root (ie: just built files).
    # - source_root : Use the source root as the artifact root (ie: all files including this one).
    root: source_root
    # Optional files to ignore when creating the artifact repo. Especially
    # useful when using the source_root above. For example, the local .gitignore
    # should probably be excluded from your artifact repo. See rsync --exclude
    # for formatting options.
    exclude:
      - /.gitignore
    # Tasks to be executed when running "boici build:tasks production"
    tasks:
      npm:
        directory: sites/all/themes/custom/custom_theme
        command: npm install
